packages:
  - packages/*
  - examples/*
  - apps/*


autoInstallPeers: false


# when a bot talks to a radio over USB.
allowBuilds:
  '@abandonware/bluetooth-hci-socket': true
  '@abandonware/noble': true
  '@serialport/bindings-cpp': true
  esbuild: true
